// const nodemailer = require('nodemailer');
// const xoauth2 = require('xoauth2');
// // const path = require('path');

// // let transporter = nodemailer.createTransport({
// //   service: 'gmail',
// //   //   auth: {
// //   //     type: 'OAuth2',
// //   //     user: process.env.MAIL_USERNAME,
// //   //     pass: process.env.MAIL_PASSWORD,
// //   //     clientId: process.env.OAUTH_CLIENTID,
// //   //     clientSecret: process.env.OAUTH_CLIENT_SECRET,
// //   //     refreshToken: process.env.OAUTH_REFRESH_TOKEN,
// //   //   },
// //   auth: {
// //     type: 'OAuth2',
// //     user: 'jmm.waqasahmed@gmail.com',
// //     pass: 'Waqas3314',
// //     clientId: '785731601160-r4frs9hukn38g6vq89f24gq59c1jl8uu.apps.googleusercontent.com',
// //     clientSecret: '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',
// //     refreshToken:
// //       '1//04_uJKVAw9I0vCgYIARAAGAQSNwF-L9Irxlh-aBM_XvQ1ebbFOA7nofgz1cTDLF9fRIQhPFP5wVgr7MPiJkSZuXWPUbSnHNSmMvM',
// //   },
// // });
// // var nodemailer = require('nodemailer');

// // let smtpTransport = nodemailer.createTransport('SMTP', {
// //   service: 'Gmail',
// //   auth: {
// //     xoauth2: xoauth2.createXOAuth2Generator({
// //       user: 'jmm.waqasahmed@gmail.com', // Your gmail address.
// //       // Not @developer.gserviceaccount.com

// //       clientId: '785731601160-r4frs9hukn38g6vq89f24gq59c1jl8uu.apps.googleusercontent.com',
// //       clientSecret: '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',
// //       refreshToken:
// //         '1//04_uJKVAw9I0vCgYIARAAGAQSNwF-L9Irxlh-aBM_XvQ1ebbFOA7nofgz1cTDLF9fRIQhPFP5wVgr7MPiJkSZuXWPUbSnHNSmMvM',
// //     }),
// //   },
// // });

// var transporter = nodemailer.createTransport({
//   service: 'gmail',
//   auth: {
//     xoauth2: xoauth2.createXOAuth2Generator({
//       user: 'jmm.waqasahmed@gmail.com', // Your gmail address.
//       //       // Not @developer.gserviceaccount.com

//       clientId: '785731601160-r4frs9hukn38g6vq89f24gq59c1jl8uu.apps.googleusercontent.com',
//       clientSecret: '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',
//       refreshToken:
//         '1//04_uJKVAw9I0vCgYIARAAGAQSNwF-L9Irxlh-aBM_XvQ1ebbFOA7nofgz1cTDLF9fRIQhPFP5wVgr7MPiJkSZuXWPUbSnHNSmMvM',
//       accessToken:
//         'ya29.a0ARrdaM-IGqVr5G6IytUeqwA6AtOR8PtFM7L26DL_XTTmJ9PIcbrLbtUFiEpbfzvc-xWQ87hD7oJjqnGovOKD6CCf9OmZ0qaI0H1UJhRxFL3BcGjpfC7iM8h7MOUsOIVIQPndNi2AWS8GTqfS2VhS3PG75ahd',
//     }),
//   },
// });

// var mailOptions = {
//   from: 'your_email_address@gmail.com',
//   to: 'my_another_email_address@gmail.com',
//   subject: 'Hello',
//   generateTextFromHTML: true,
//   html: '<b>Hello world</b>',
// };

// // smtpTransport.sendMail(mailOptions, function(error, response) {
// //   if (error) {
// //     console.log(error);
// //   } else {
// //     console.log(response);
// //   }
// //   smtpTransport.close();
// // });
// // const hbs = require('nodemailer-express-handlebars');

// // initialize nodemailer
// // var transporter = nodemailer.createTransport({
// //   service: 'gmail',
// //   auth: {
// //     user: 'wiki3314@gmail.com',
// //     pass: '03315593314',
// //   },
// // });
// // var transport = nodemailer.createTransport({
// //     host: "smtp.mailtrap.io",
// //     port: 2525,
// //     auth: {
// //       user: "1a2b3c4d5e6f7g", //generated by Mailtrap
// //       pass: "1a2b3c4d5e6f7g" //generated by Mailtrap
// //     }
// //   });

// // point to the template folder
// // const handlebarOptions = {
// //   viewEngine: {
// //     partialsDir: path.resolve('./views/'),
// //     defaultLayout: false,
// //   },
// //   viewPath: path.resolve('./views/'),
// // };

// // // use a template file with nodemailer
// // transporter.use('compile', hbs(handlebarOptions));

// // var mailOptions = {
// //   from: 'wiki3314@gmail.com', // sender address
// //   to: 'jmm.waqasahmed@gmail.com', // list of receivers
// //   subject: 'Welcome!',
// //   //   template: 'email', // the name of the template file i.e email.handlebars
// //   //   context: {
// //   //     name: 'Adebola', // replace {{name}} with Adebola
// //   //     company: 'My Company', // replace {{company}} with My Company
// //   //   },
// // };

// export const sendEmail = userData => {
//   //   return new Promise((resolve, rejects) => {
//   // trigger the sending of the E-mail
//   //   transporter.sendMail(
//   //     {
//   //       from: 'jmm.waqasahmed@gmail.com', // list of receivers
//   //       to: 'wiki3314@gmail.com', // sender address
//   //       subject: 'Welcome!',
//   //       text: 'hiiiiiiiiiii',
//   //       //   template: 'email', // the name of the template file i.e email.handlebars
//   //       //   context: {
//   //       //     name: 'Adebola', // replace {{name}} with Adebola
//   //       //     company: 'My Company', // replace {{company}} with My Company
//   //       //   },
//   //     },
//   //     (error, info) => {
//   //       if (error) {
//   //         return console.log(error);
//   //         //   rejects(error);
//   //       }
//   //       console.log('Message sent: ' + info.response);
//   //       // resolve(info.response);
//   //     },
//   //   );

//   transporter.sendMail(
//     {
//       from: 'jmm.waqasahmed@gmail.com', // list of receivers
//       to: 'wiki3314@gmail.com', // sender address
//       subject: 'Hello',
//       generateTextFromHTML: true,
//       html: '<b>Hello world</b>',
//     },
//     function(error, response) {
//       if (error) {
//         console.log(error);
//       } else {
//         console.log(response);
//       }
//       //   smtpTransport.close();
//     },
//   );
//   //   });
// };
